
let sourceDir = @"C:\Program Files\devDept Software\Eyeshot 2023\Bin\"
let binDir = "binaries"
let frameworkTfm = "net472"
let coreTfm = "net60"
let wpfFolder = "wpf"
let winFormsFolder = "winforms"
let eyeshotDllPattern = "devdept.*.dll"
let eyeshotXmlPattern = "devdept.*.xml"
let packageOutput = "packages"
let eyeshotCoreFiles = "devDept.Eyeshot.*"
let eyeshotWinFormsFiles = "devDept.Eyeshot.Control.Win.*"
let eyeshotWpfFiles = "devDept.Eyeshot.Control.Wpf.*"